Begin the refactor, the actual content is partial and a little bit old.

diff --git a/link b/link
--- a/link
+++ b/link
@@ -1,4 +1,120 @@
 #!/bin/sh
+# This a modified version of holman's bootstrap script
 
-# ack
-ln -sf $(pwd)/ack/ackrc $HOME/.ackrc
+DOTFILES_ROOT="`pwd`"
+
+set -e
+
+echo ''
+
+info () {
+    printf "  [ \033[00;34m..\033[0m ] $1"
+}
+
+user () {
+    printf "  [ \033[0;33m?\033[0m ] $1 "
+}
+
+success () {
+    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+}
+
+fail () {
+    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+    echo ''
+    exit
+}
+
+setup_gitconfig () {
+    if ! [ -f git/gitconfig.symlink ]
+    then
+        info "setup gitconfig\n"
+        user ' - What is your github author name?'
+        read -e git_authorname
+        user ' - What is your github author email?'
+        read -e git_authoremail
+
+        sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" git/gitconfig.symlink.example > git/gitconfig.symlink
+
+        success 'gitconfig'
+    fi
+}
+
+link_files () {
+  ln -fs $1 $2
+  success "linked $1 to $2"
+}
+
+install_dotfiles () {
+
+    info "installing dotfiles\n"
+
+    overwrite_all=false
+    backup_all=false
+    skip_all=false
+
+    for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
+    do
+        dest="$HOME/.`basename \"${source%.*}\"`"
+
+        if [ -f $dest ] || [ -d $dest ]
+        then
+
+            overwrite=false
+            backup=false
+            skip=false
+
+            if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
+            then
+
+                user "File already exists: `basename $source`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
+                read -n 1 action
+
+                case "$action" in
+                  o )
+                    overwrite=true;;
+                  O )
+                    overwrite_all=true;;
+                  b )
+                    backup=true;;
+                  B )
+                    backup_all=true;;
+                  s )
+                    skip=true;;
+                  S )
+                    skip_all=true;;
+                  * )
+                    ;;
+                esac
+
+            fi
+
+            if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
+            then
+                rm -rf $dest
+                success "removed $dest"
+            fi
+
+            if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
+            then
+                mv $dest $dest\.backup
+                success "moved $dest to $dest.backup"
+            fi
+
+            if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
+            then
+                link_files $source $dest
+            else
+                success "skipped $source"
+            fi
+        else
+            link_files $source $dest
+        fi
+    done
+}
+
+setup_gitconfig
+install_dotfiles
+
+echo ''
+
